# .github/workflows/python_ci.yml

name: Python CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term

    - name: Upload coverage to Coveralls
      if: success()
      # REMOVE the 'env:' block here.
      # Coveralls will auto-detect GitHub Actions and use the default GITHUB_TOKEN.
      run: |
        # Optional: You can keep diagnostic echoes for GITHUB_TOKEN if curious,
        # but don't explicitly set COVERALLS_REPO_TOKEN or COVERALLS_SERVICE_NAME
        # unless specifically needed for a non-standard setup.
        # echo "GITHUB_TOKEN is set (first 5 chars): ${GITHUB_TOKEN:0:5}..."
        coveralls