# .github/workflows/python_ci.yml

name: Python CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term

    # Ensure this step is correctly indented under 'steps:'
    - name: Upload coverage to Coveralls
      if: success()
      # 'env:' block must be at the same indentation level as 'name:', 'if:', and 'run:'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_SERVICE_NAME: github-actions
      run: |
        # --- Diagnostic: Print environment variables to confirm ---
        echo "Checking environment variables before coveralls command:"
        echo "COVERALLS_REPO_TOKEN is set (first 5 chars): ${COVERALLS_REPO_TOKEN:0:5}..."
        echo "COVERALLS_SERVICE_NAME is set: ${COVERALLS_SERVICE_NAME}"
        echo "----------------------------------------------------"
        # --- End Diagnostic ---

        coveralls # This command automatically looks for coverage.xml